# Generated by Django 6.0.7 on 2026-07-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Заезд')),
                ('check_out', models.DateField(verbose_name='Выезд')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Гостей')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('promo_code', models.CharField(blank=True, max_length=50, verbose_name='Промокод')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер домика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cottage_type', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('luxury', 'Люкс')], default='standard', max_length=20, verbose_name='Тип')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('max_guests', models.PositiveIntegerField(default=4, verbose_name='Макс. гостей')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Спальни')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Ванные')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('has_kitchen', models.BooleanField(default=True, verbose_name='Кухня')),
                ('has_bbq', models.BooleanField(default=False, verbose_name='Мангал')),
                ('image', models.ImageField(blank=True, upload_to='cottages/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('latitude', models.FloatField(default=55.7558, verbose_name='Широта')),
                ('longitude', models.FloatField(default=37.6173, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Коттедж',
                'verbose_name_plural': 'Коттеджи',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
