# Generated by Django 6.0.7 on 2026-08-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='С')),
                ('end_date', models.DateField(verbose_name='По')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='bookings.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Закрытая дата',
                'verbose_name_plural': 'Закрытые даты',
                'ordering': ['start_date'],
            },
        ),
    ]
