# Generated by Django 6.0.7 on 2026-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_blockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='description_cs',
            field=models.TextField(blank=True, verbose_name='Описание (CS)'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='name_cs',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (CS)'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
    ]
