# Generated by Django 6.0.7 on 2026-08-20 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_review_options_review_cottage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cottages/gallery/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Фото коттеджа',
                'verbose_name_plural': 'Фотографии коттеджа',
                'ordering': ['order', 'id'],
            },
        ),
    ]
