# Generated by Django 6.0.7 on 2026-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='latitude',
            field=models.FloatField(default=41.622706, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='longitude',
            field=models.FloatField(default=42.308329, verbose_name='Долгота'),
        ),
    ]
