# Generated by Django 6.0.7 on 2026-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=4, verbose_name='Код')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Код подтверждения телефона',
                'verbose_name_plural': 'Коды подтверждения телефона',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='payout_card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры карты'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, verbose_name='Способ вывода'),
        ),
    ]
