# Generated by Django 6.0.7 on 2026-08-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, upload_to='tips/', verbose_name='Картинка'),
        ),
    ]
