# Generated by Django 6.0.7 on 2026-09-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
