# Generated by Django 6.0.7 on 2026-08-04 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('booking_payment', 'Оплата брони'), ('task_reward', 'Награда за задание')], max_length=20, verbose_name='Источник')),
                ('source_object_id', models.PositiveIntegerField(verbose_name='ID источника')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма основания')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ставка')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма комиссии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL, verbose_name='Реферал')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL, verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Реферальная комиссия',
                'verbose_name_plural': 'Реферальные комиссии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('referral_booking_bonus', 'Бонус за бронь реферала'), ('referral_task_bonus', 'Бонус за задание реферала'), ('task_reward', 'Награда за задание'), ('withdrawal', 'Вывод средств'), ('booking_payment_from_balance', 'Оплата брони с баланса'), ('admin_adjustment', 'Корректировка администратором')], max_length=30, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='completed', max_length=20, verbose_name='Статус')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('related_object_type', models.CharField(blank=True, max_length=30, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к списанию')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к выплате')),
                ('method', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, verbose_name='Способ вывода')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры карты')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('paid', 'Оплачено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий администратора')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод средств',
                'verbose_name_plural': 'Заявки на вывод средств',
                'ordering': ['-requested_at'],
            },
        ),
    ]
