# Generated by Django 6.0.7 on 2026-08-04 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('platform', models.CharField(choices=[('vk', 'VK'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Платформа')),
                ('reward_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда от')),
                ('reward_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vk', 'VK'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Платформа')),
                ('submitted_link', models.URLField(verbose_name='Ссылка на публикацию')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма начисления')),
                ('admin_comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на задание',
                'verbose_name_plural': 'Заявки на задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
